Improving EN translation
RedAlex/FiveM-BanSql pull request #24
Opened 2019-06-24 13:26 UTC by Zeemahh

Have better formality and legibility. Also be more specific and improve grammar in some of the options.

2019-10-17 23:58 UTC, Zeemahh commented
Fixed conflicts.

2019-10-18 00:10 UTC, RedAlex commented on config.lua
> +	banoff        = "Manually ban a (offline) player",
Manually are not need to be write.
It's just an in game help to say what the command do.
"Ban an offline player" Will be better no?

2019-10-18 00:12 UTC, RedAlex reviewed
Line 82 to be more precise

2019-10-18 00:14 UTC, lucmen requested changes

2019-10-18 00:14 UTC, lucmen commented on config.lua
> +	banoff        = "Manually ban a (offline) player",
banoff     = "ban an offline player",

2019-10-18 00:18 UTC, RedAlex approved these changes

2019-10-18 00:18 UTC, merged